### ISSUE TITLE
EXPLAIN fails on Broadcast JOINs

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#527]
This looks like not very easy to solve with our current distributed explain logic where we don't have task dependency logic implemented yet as in real-time or task-tracker executors. Besides, that decision aims to prevent any side-effects (i.e., fetching shards) to happen during an EXPLAIN command. 

@marcocitus may give a more detailed description in case the above has any missing/wrong information.

Steps to re-produce with two worker nodes:

``` SQL

postgres= CREATE TABLE test_16 (a int);
CREATE TABLE
Time: 7.704 ms

postgres= select master_create_distributed_table('test_16', 'a', 'hash');
 master_create_distributed_table 
---------------------------------

(1 row)

Time: 5.182 ms
postgres= select master_create_worker_shards('test_16', 16, 1);
 master_create_worker_shards 
-----------------------------

(1 row)

Time: 277.549 ms

postgres= CREATE TABLE test_1 (a int);
CREATE TABLE
Time: 10.395 ms
postgres= select master_create_distributed_table('test_1', 'a', 'hash');
 master_create_distributed_table 
---------------------------------

(1 row)

Time: 10.057 ms
postgres= select master_create_worker_shards('test_1', 1,  1);
 master_create_worker_shards 
-----------------------------

(1 row)

Time: 32.588 ms


postgres= set citus.explain_all_tasks to on;
SET
Time: 0.774 ms


postgres= EXPLAIN SELECT * FROM test_16 t16, test_1 t1 WHERE t16.a = t1.a;
WARNING:  could not receive query results from localhost:9701
DETAIL:  Client error: relation "test_1_102088" does not exist
WARNING:  could not receive query results from localhost:9701
DETAIL:  Client error: relation "test_1_102088" does not exist
WARNING:  could not receive query results from localhost:9701
DETAIL:  Client error: relation "test_1_102088" does not exist
WARNING:  could not receive query results from localhost:9701
DETAIL:  Client error: relation "test_1_102088" does not exist
WARNING:  could not receive query results from localhost:9701
DETAIL:  Client error: relation "test_1_102088" does not exist
WARNING:  could not receive query results from localhost:9701
DETAIL:  Client error: relation "test_1_102088" does not exist
WARNING:  could not receive query results from localhost:9701
DETAIL:  Client error: relation "test_1_102088" does not exist
WARNING:  could not receive query results from localhost:9701
DETAIL:  Client error: relation "test_1_102088" does not exist
                                          QUERY PLAN                                          
----------------------------------------------------------------------------------------------
 Distributed Query into pg_merge_job_0004
   Executor: Real-Time
   Task Count: 16
   Tasks Shown: All
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Merge Join  (cost=359.57..860.00 rows=32512 width=8)
               Merge Cond: (t16.a = t1.a)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t16.a
                     ->  Seq Scan on test_16_102008 t16  (cost=0.00..35.50 rows=2550 width=4)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t1.a
                     ->  Seq Scan on test_1_102088 t1  (cost=0.00..35.50 rows=2550 width=4)
   ->  Task
         Error: Could not get remote plan.
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Merge Join  (cost=359.57..860.00 rows=32512 width=8)
               Merge Cond: (t16.a = t1.a)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t16.a
                     ->  Seq Scan on test_16_102010 t16  (cost=0.00..35.50 rows=2550 width=4)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t1.a
                     ->  Seq Scan on test_1_102088 t1  (cost=0.00..35.50 rows=2550 width=4)
   ->  Task
         Error: Could not get remote plan.
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Merge Join  (cost=359.57..860.00 rows=32512 width=8)
               Merge Cond: (t16.a = t1.a)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t16.a
                     ->  Seq Scan on test_16_102012 t16  (cost=0.00..35.50 rows=2550 width=4)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t1.a
                     ->  Seq Scan on test_1_102088 t1  (cost=0.00..35.50 rows=2550 width=4)
   ->  Task
         Error: Could not get remote plan.
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Merge Join  (cost=359.57..860.00 rows=32512 width=8)
               Merge Cond: (t16.a = t1.a)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t16.a
                     ->  Seq Scan on test_16_102014 t16  (cost=0.00..35.50 rows=2550 width=4)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t1.a
                     ->  Seq Scan on test_1_102088 t1  (cost=0.00..35.50 rows=2550 width=4)
   ->  Task
         Error: Could not get remote plan.
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Merge Join  (cost=359.57..860.00 rows=32512 width=8)
               Merge Cond: (t16.a = t1.a)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t16.a
                     ->  Seq Scan on test_16_102016 t16  (cost=0.00..35.50 rows=2550 width=4)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t1.a
                     ->  Seq Scan on test_1_102088 t1  (cost=0.00..35.50 rows=2550 width=4)
   ->  Task
         Error: Could not get remote plan.
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Merge Join  (cost=359.57..860.00 rows=32512 width=8)
               Merge Cond: (t16.a = t1.a)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t16.a
                     ->  Seq Scan on test_16_102018 t16  (cost=0.00..35.50 rows=2550 width=4)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t1.a
                     ->  Seq Scan on test_1_102088 t1  (cost=0.00..35.50 rows=2550 width=4)
   ->  Task
         Error: Could not get remote plan.
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Merge Join  (cost=359.57..860.00 rows=32512 width=8)
               Merge Cond: (t16.a = t1.a)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t16.a
                     ->  Seq Scan on test_16_102020 t16  (cost=0.00..35.50 rows=2550 width=4)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t1.a
                     ->  Seq Scan on test_1_102088 t1  (cost=0.00..35.50 rows=2550 width=4)
   ->  Task
         Error: Could not get remote plan.
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Merge Join  (cost=359.57..860.00 rows=32512 width=8)
               Merge Cond: (t16.a = t1.a)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t16.a
                     ->  Seq Scan on test_16_102022 t16  (cost=0.00..35.50 rows=2550 width=4)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Sort Key: t1.a
                     ->  Seq Scan on test_1_102088 t1  (cost=0.00..35.50 rows=2550 width=4)
   ->  Task
         Error: Could not get remote plan.
 Master Query
   ->  Seq Scan on pg_merge_job_0004  (cost=0.00..0.00 rows=0 width=0)
(102 rows)

Time: 315.863 ms
postgres=# 

```

**Comment by onderkalaci** [comment]
Fixed by #1018, closing the issue.

**Comment by marcocitus** [comment]
Well, the issue still exists, there are just more ways to avoid running into it now.

**Comment by onderkalaci** [comment]
> Fixed by #1018, closing the issue.

Fixed for tables which are created via `create_reference_table` but still exists for some other combinations of rep factor / shard count.

**Comment by onderkalaci** [comment]
I think we have a couple of such issues. In summary, we fix the issue for reference tables but the issue still exists for other small tables (i.e., `shardCount < LargeTableCount`).  I'm happy to close such issues given that 

- We'll be recommending reference tables over small tables 
- We have a way to upgrade existing small tables to reference tables via #1075  

@marcocitus @ozgune @sumedhpathak Any suggesstions here?

**Comment by marcocitus** [comment]
We could consider remove the data fetch logic altogether and disallow local/broadcast joins between shards that are not on the same machine.

**Comment by velioglu** [comment]
We have disallowed local/broadcast joins between shards that are not on the same machine by #1915 #1974 and #1980. So, these types of joins can be planned using repartition join logic.
